// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenExpenseApp.Data;

#nullable disable

namespace OpenExpenseApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenExpenseApp.Models.Expense", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnName("category")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnName("description");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnName("is_recurring");

                    b.Property<int>("PaymentMethod")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnName("received_date")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("expenses", "public");
                });

            modelBuilder.Entity("OpenExpenseApp.Models.Income", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnName("gross_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IncomeType")
                        .HasMaxLength(50)
                        .HasColumnName("income_type")
                        .IsRequired();

                    b.Property<bool>("IsTaxable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_taxable")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnName("received_date")
                        .HasColumnType("date");

                    b.Property<string>("SourceName")
                        .HasMaxLength(50)
                        .HasColumnName("source_name")
                        .IsRequired();

                    b.Property<decimal?>("TaxWithheld")
                        .HasColumnName("tax_withheld")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("incomes", "public");
                });

            modelBuilder.Entity("OpenExpenseApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnName("email")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnName("full_name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnName("password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("OpenExpenseApp.Models.UserExpense", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnName("gross_amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnName("notes");

                    b.Property<int>("PaymentMethod")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnName("received_date")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_expenses", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
